automation:
- alias: Bathroom Master - Scene Controller - Button 5 - Press
  description: ''
  triggers:
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed
    id: Trigger_Press_1x
    trigger: event
    alias: Press 1x
  - alias: Press 2x
    event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed2x
    id: Trigger_Press_2x
    trigger: event
  - alias: Press 3x
    event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed3x
    id: Trigger_Press_3x
    trigger: event
  - alias: Press 4x
    event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed4x
    id: Trigger_Press_4x
    trigger: event
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed5x
    id: Trigger_Press_5x
    trigger: event
    alias: Press 5x
    enabled: false
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyHeldDown
    id: Trigger_Press_Hold
    trigger: event
    alias: Press Hold
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyReleased
    id: Trigger_Press_Release
    trigger: event
    alias: Press Release
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_1x
      - condition: template
        value_template: '{{ is_state(light_source, ''on'') }}'
      sequence:
      - action: scene.create
        metadata: {}
        data:
          scene_id: '{{device_id}}_{{button_name}}_last_on

            '
          snapshot_entities: '{{ expand(light_source) | map(attribute=''entity_id'')
            | list }}

            '
      - action: input_select.select_first
        metadata: {}
        data: {}
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
      - target:
          entity_id: '{{light_source}}

            '
        data: {}
        action: light.turn_off
      alias: Press 1X - 1 - Turn Off
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_1x
      - condition: template
        value_template: '{{ is_state(light_source, ''off'') }}'
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
            | lower | replace(" ", "_") }}

            '
      alias: Press 1X - 2 - Turn On
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_2x
      sequence:
      - action: input_select.select_next
        metadata: {}
        data:
          cycle: true
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
      alias: Press 2X
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_3x
      sequence:
      - action: input_select.select_last
        metadata: {}
        data: {}
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: 'scene.{{device_id}}_{{button_name}}_default

            '
        enabled: false
      - action: adaptive_lighting.apply
        metadata: {}
        data:
          entity_id: 'switch.adaptive_lighting_{{area_name}}

            '
        enabled: false
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
            | lower | replace(" ", "_") }}

            '
      alias: Press 3X
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_4x
      sequence:
      - action: adaptive_lighting.change_switch_settings
        metadata: {}
        data:
          entity_id: 'switch.adaptive_lighting_{{area_name}}

            '
          prefer_rgb_color: '{{ not state_attr(''switch.adaptive_lighting_''~area_name,
            ''configuration'')[''prefer_rgb_color''] }}

            '
        alias: Toggle Prefer_RGB_Color
      - alias: Toggle Prefer_RGB_Color
        action: adaptive_lighting.change_switch_settings
        metadata: {}
        data:
          entity_id: 'switch.adaptive_lighting_bathroom_master

            '
          prefer_rgb_color: '{{ not state_attr(''switch.adaptive_lighting_bathroom_master'',
            ''configuration'')[''prefer_rgb_color''] }}

            '
        enabled: false
      alias: Press 4X
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_5x
      sequence: []
      alias: Press 5X - 1 - State ON
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_Hold
      sequence:
      - action: automation.toggle
        target:
          entity_id: 'automation.{{area_name}}_motion_sensor

            '
        data: {}
      alias: Press Hold - Automatic Lights Toggle
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_Release
      sequence:
      - if:
        - condition: state
          entity_id: light.office_group_all_lights
          state: 'off'
        then:
        - action: switch.turn_off
          target:
            entity_id:
            - switch.zen32_scene_controller_d966bfe5eaa4645f72ff45022220e12d_button_1_indication_binary
          data: {}
        enabled: false
      alias: Press Hold - 2 - Release
    enabled: true
  trigger_variables:
    device_id: a810acaa571a62d588d1d4c5afc5de31
    button_name: button_5
    light_source: light.a810acaa571a62d588d1d4c5afc5de31_button_5_lights
    button_number: '{{ button_name.split(''_'')[1] }}'
    property_key: '{{ ''00'' ~ button_number }}'
  variables:
    area_name: '{{ area_name(trigger.event.data.device_id) | lower | replace('' '',
      ''_'') }}'
  mode: single
  '#id': '1760476939303'
  enabled: false
- alias: Bathroom Master - Scene Controller - Button 5 - LED Indicator
  description: Toggles LED and changes colors based on Entity statuses
  triggers:
  - entity_id:
    - light.a810acaa571a62d588d1d4c5afc5de31_button_5_lights
    to: 'on'
    from: 'off'
    id: Button_Source_On
    trigger: state
    enabled: true
  - entity_id:
    - light.a810acaa571a62d588d1d4c5afc5de31_button_5_lights
    to: 'off'
    from: 'on'
    id: Button_Source_Off
    trigger: state
    enabled: true
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - entity_id:
    - automation.bathroom_master_motion_sensor
    from: 'off'
    to: 'on'
    id: AutomaticLights_On
    trigger: state
    enabled: true
  - entity_id:
    - automation.bathroom_master_motion_sensor
    from: 'on'
    to: 'off'
    id: AutomaticLights_Off
    trigger: state
    enabled: true
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Button_Source_On
      sequence:
      - data: {}
        action: switch.turn_on
        target:
          entity_id: '{{led_switch_name}}

            '
    - conditions:
      - condition: trigger
        id:
        - Button_Source_Off
      sequence:
      - action: switch.turn_off
        target:
          entity_id: '{{led_switch_name}}

            '
        data: {}
    - conditions:
      - condition: trigger
        id:
        - AutomaticLights_On
      sequence:
      - target:
          device_id: '{{device_id}}

            '
        data:
          parameter: '6'
          value: Green
          device_id: '{{device_id}}

            '
        action: zwave_js.set_config_parameter
    - conditions:
      - condition: trigger
        id:
        - AutomaticLights_Off
      sequence:
      - target:
          device_id: '{{device_id}}

            '
        data:
          parameter: '6'
          value: Red
          device_id: '{{device_id}}

            '
        action: zwave_js.set_config_parameter
    enabled: true
  variables:
    replace_light: light.a810acaa571a62d588d1d4c5afc5de31_button_5_lights
    replace_automation: automation.bathroom_master_motion_sensor
    device_id: a810acaa571a62d588d1d4c5afc5de31
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    led_number: '{{ (button_number | int % 5) + 1 }}'
    led_switch_name: '{{ ''switch.zen32_scene_controller_'' ~device_id~ ''_button_''
      ~led_number~ ''_indication_binary'' }}'
  mode: single
  '#id': '1760477189842'
  enabled: false
- alias: Bathroom Master - Scene Controller - Button 5 - Activate Scene
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_select.a810acaa571a62d588d1d4c5afc5de31_button_5_scene_input
    id: Trigger_SceneInput
    enabled: true
  - trigger: state
    entity_id:
    - scene.a810acaa571a62d588d1d4c5afc5de31_button_5_adaptive_lighting_reset
    to: null
    id: Trigger_AdaptiveLightingReset
    enabled: false
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
        | lower | replace(" ", "_") }}

        '
    enabled: false
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
        | lower | replace(" ", "_") }}

        '
    enabled: true
    alias: Activate current scene in Scene Selector
  - if:
    - condition: template
      value_template: '{{ states(''input_select.'' + device_id + ''_button_5_scene_input'')
        == ''Adaptive Lighting Reset'' }}

        '
      alias: Scene Selector value == Adaptive Lighting Reset
    then:
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - action: adaptive_lighting.apply
      metadata: {}
      data:
        entity_id: switch.adaptive_lighting_{{area_name}}
      alias: Apply Adaptive Lighting Settings to current Area
  variables:
    device_id: a810acaa571a62d588d1d4c5afc5de31
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    area_name: '{{ area_name(trigger.entity_id) | lower | replace('' '', ''_'') }}'
  mode: single
  '#id': '1760477049992'
  enabled: false
